---
- name: for_vagrant_box | udev ルールを削除する
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/70-persistent-net.rules
    force: yes
    state: link

- name: for_vagrant_box | 接続してきたクライアントの名前解決をしない
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: '^#UseDNS yes$'
    line: 'UseDNS no'

- name: for_vagrant_box | 仮想イメージサイズを小さくする
  shell: |-
    yum -y clean all
    dd if=/dev/zero of=/EMPTY bs=1M
    rm -f /EMPTY

- name: for_vagrant_box | シャットダウンする
  command:
    poweroff

- name: for_vagrant_box | ゲストが完全に終了するまで待つ
  command:
    VBoxManage showvminfo {{ inventory_hostname }}
  register: return
  until: return.stdout | search('powered off')
  delay: 10
  retries: 6
  delegate_to: 127.0.0.1

- name: for_vagrant_box | ネットワークカードを NAT に戻す
  command:
    VBoxManage modifyvm {{ inventory_hostname }} --nic1 nat {% if inventory_hostname == 'CentOS-5' %}--nictype1 virtio{% endif %}
  delegate_to: 127.0.0.1

- name: for_vagrant_box | vagrant box を playbooks ディレクトリに出力する
  command:
    /opt/vagrant/bin/vagrant package --base {{ inventory_hostname }} --output {{ vagrant_box_name }}.box
  delegate_to: 127.0.0.1

- name: for_vagrant_box | vagrant box を 登録する
  command:
    /opt/vagrant/bin/vagrant box add {{ vagrant_box_name }} {{ vagrant_box_name }}.box
  delegate_to: 127.0.0.1
