---
# Ansible 1.9.3 では yum: name=* state=latest が失敗する。
# https://github.com/ansible/ansible-modules-core/issues/2013
- name: virtualbox_guest_additions | システムをアップデートする
  command:
    yum -y update

- include: reboot.yml

- name: virtualbox_guest_additions | fact のキャッシュを更新する
  setup:

- name: virtualbox_guest_additions | VirtualBox Guest Additions のビルドに必要なパッケージをインストールする
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - kernel-devel-{{ ansible_kernel }}
    - perl

- include: reboot.yml

- name: virtualbox_guest_additions | VirtualBox Guest Additions の iso をローカルの /tmp にダウンロードする
  get_url:
    url: "{{ vboxguestaddtions_iso }}"
    dest: /tmp/{{ vboxguestaddtions_iso | basename }}
  delegate_to: 127.0.0.1

- name: virtualbox_guest_additions | ダウンロードした iso を転送する
  copy:
    src: /tmp/{{ vboxguestaddtions_iso | basename }}
    dest: /tmp/{{ vboxguestaddtions_iso | basename }}

- name: virtualbox_guest_additions | iso をマウントする
  mount:
    name: /media/VBoxGuestAdditions
    src: /tmp/{{ vboxguestaddtions_iso | basename }}
    fstype: iso9660
    opts: loop,ro
    state: mounted

- name: virtualbox_guest_additions | VBoxLinuxAdditions.run を実行する（fail するが Box 作成に影響無し）
  command:
    sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
  ignore_errors: yes

- name: virtualbox_guest_additions | マウントを解除する
  mount:
    name: /media/VBoxGuestAdditions
    src: /tmp/{{ vboxguestaddtions_iso | basename }}
    fstype: iso9660
    state: unmounted

- name: virtualbox_guest_additions | マウントエントリを削除する
  lineinfile:
    dest: /etc/fstab
    regexp: '/media/VBoxGuestAdditions'
    state: absent

- name: virtualbox_guest_additions | 不要物を削除する
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - /tmp/{{ vboxguestaddtions_iso | basename}}
    - /media/VBoxGuestAdditions
